version: '3.8'
services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: /data/db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  redis:
    container_name: redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

volumes:
  mongo-data: